name: Build Signed APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Android
        uses: android-actions/setup-android@v3
          
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Create keystore file
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > app/release.keystore
          
      - name: Build Signed Release APK
        run: ./gradlew assembleRelease
        env:
          RELEASE_KEYSTORE_FILE: release.keystore
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          
      - uses: actions/upload-artifact@v4
        with:
          name: signed-app
          path: app/build/outputs/apk/release/app-release.apk
